# Application
base.url=https://demoqa.com

# Browser
browser=chrome

# Timeouts (in seconds)
implicit.wait=0
explicit.wait=20
page.load.timeout=30

# Selenium Grid
grid.enabled=false
grid.url=http://localhost:4444/wd/hub

#Parallel
parallel.enabled=true
thread.count=3